# 可能是解析库的原因，如果类似下面这句放到任何[]之下的话，都会被认为是[]下的所属，故类似这种没有[]的，都得放到前面来
sentry_dsn = "http://da3139a4014c431a9024a3b0b3eb9da7:c387db95d2384d83b594f984cf303420@47.99.39.114:9000/4"

[base_info]
    version = "0.1"
    name = "samh-operation"
    port = 10001

[log_info_item]
    level="debug" #debug info warn error panic fatal
    encoding="console"     # 输出格式 console 或 json，建议正式环境用json，其他console（简洁）
    path_filename = "/data1/logs/samh/operation/log.log"
    # max_size=  128    # 每个日志文件保存的最大尺寸 单位：M
    # max_backups= 30   # 日志文件最多保存多少个备份
    # max_age=     7    # 文件最多保存多少天
    compress=true

[internal_server]
    [internal_server.vip]
        url = "http://47.98.52.122:9091/app_api/v5/activity_vip"
        time_out = 500  # millisecond

[db_arr]
    [db_arr.operation]
        type = "mysql"
        host = "47.99.39.114"
        port = 3306
        user = "recommend"
        password = "R1QaL1^G0Fpv8^ZT"
        db_name = "samh_operation"
        max_conns = 20
        time_out = 300
        log_path = "/data1/logs/samh/operation/db/"
        log_name = "sql.log"
        [db_arr.operation.table_name]
            a = "a"
            b = "b"
    [db_arr.samh]
        type = "mysql"
        host = "47.99.39.114"
        port = 3306
        user = "recommend"
        password = "R1QaL1^G0Fpv8^ZT"
        db_name = "samh"
        max_conns = 20
        time_out = 300
        log_path = "/data1/logs/samh/operation/db/"
        log_name = "sql.log"
        [db_arr.samh.table_name]
            c = "c"
            d = "d"
[redis_item]
    network="tcp"
    addr = "127.0.0.1:6379"
    password = "abc123"
    max_retries=3
    pool_size=200

[redis_cluster_item]
    master_addr_arr = ["47.99.39.114:7000","47.99.39.114:7001","47.99.39.114:7002"]
    slave_addr_arr = ["47.99.39.114:7003","47.99.39.114:7004","47.99.39.114:7005"]
    password = "gUcAFcWf#Dg4He7R"
    max_retries=3
    pool_size=200

[web]
    http_request_timeout=5 # s
